# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 793)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/log_oxigen_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Canada))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget_General = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget_General.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_General.setObjectName("tabWidget_General")
        self.tab_Parameters = QtWidgets.QWidget()
        self.tab_Parameters.setObjectName("tab_Parameters")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_Parameters)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.tab_Parameters)
        self.label.setMinimumSize(QtCore.QSize(55, 0))
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.edt_Path = QtWidgets.QLineEdit(self.tab_Parameters)
        self.edt_Path.setObjectName("edt_Path")
        self.horizontalLayout_3.addWidget(self.edt_Path)
        self.btn_SelectDir = QtWidgets.QToolButton(self.tab_Parameters)
        self.btn_SelectDir.setObjectName("btn_SelectDir")
        self.horizontalLayout_3.addWidget(self.btn_SelectDir)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.tab_Parameters)
        self.label_2.setMinimumSize(QtCore.QSize(55, 0))
        self.label_2.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.date_From = QtWidgets.QDateEdit(self.tab_Parameters)
        self.date_From.setCalendarPopup(True)
        self.date_From.setObjectName("date_From")
        self.horizontalLayout_4.addWidget(self.date_From)
        self.label_3 = QtWidgets.QLabel(self.tab_Parameters)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.date_To = QtWidgets.QDateEdit(self.tab_Parameters)
        self.date_To.setCalendarPopup(True)
        self.date_To.setDate(QtCore.QDate(2100, 1, 1))
        self.date_To.setObjectName("date_To")
        self.horizontalLayout_4.addWidget(self.date_To)
        self.frame_3 = QtWidgets.QFrame(self.tab_Parameters)
        self.frame_3.setMinimumSize(QtCore.QSize(16, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.label_6 = QtWidgets.QLabel(self.tab_Parameters)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.spin_perfTrigger = QtWidgets.QDoubleSpinBox(self.tab_Parameters)
        self.spin_perfTrigger.setDecimals(1)
        self.spin_perfTrigger.setMinimum(0.5)
        self.spin_perfTrigger.setMaximum(999.0)
        self.spin_perfTrigger.setSingleStep(0.5)
        self.spin_perfTrigger.setProperty("value", 3.5)
        self.spin_perfTrigger.setObjectName("spin_perfTrigger")
        self.horizontalLayout_4.addWidget(self.spin_perfTrigger)
        self.label_7 = QtWidgets.QLabel(self.tab_Parameters)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.frame_4 = QtWidgets.QFrame(self.tab_Parameters)
        self.frame_4.setMinimumSize(QtCore.QSize(16, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.label_4 = QtWidgets.QLabel(self.tab_Parameters)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spin_contextLOL = QtWidgets.QSpinBox(self.tab_Parameters)
        self.spin_contextLOL.setMaximum(100)
        self.spin_contextLOL.setSingleStep(5)
        self.spin_contextLOL.setProperty("value", 10)
        self.spin_contextLOL.setObjectName("spin_contextLOL")
        self.horizontalLayout_4.addWidget(self.spin_contextLOL)
        self.label_5 = QtWidgets.QLabel(self.tab_Parameters)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.frame_5 = QtWidgets.QFrame(self.tab_Parameters)
        self.frame_5.setMinimumSize(QtCore.QSize(16, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.chk_splitFilePath = QtWidgets.QCheckBox(self.tab_Parameters)
        self.chk_splitFilePath.setChecked(True)
        self.chk_splitFilePath.setObjectName("chk_splitFilePath")
        self.horizontalLayout_4.addWidget(self.chk_splitFilePath)
        self.frame_6 = QtWidgets.QFrame(self.tab_Parameters)
        self.frame_6.setMinimumSize(QtCore.QSize(16, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4.addWidget(self.frame_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.tab_Parameters)
        self.label_8.setMinimumSize(QtCore.QSize(55, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.edt_output = QtWidgets.QLineEdit(self.tab_Parameters)
        self.edt_output.setObjectName("edt_output")
        self.horizontalLayout.addWidget(self.edt_output)
        self.frame = QtWidgets.QFrame(self.tab_Parameters)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.tab_Parameters)
        self.frame_2.setMinimumSize(QtCore.QSize(16, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.chk_AutoOpen = QtWidgets.QCheckBox(self.tab_Parameters)
        self.chk_AutoOpen.setChecked(True)
        self.chk_AutoOpen.setObjectName("chk_AutoOpen")
        self.horizontalLayout.addWidget(self.chk_AutoOpen)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.edt_console = QtWidgets.QPlainTextEdit(self.tab_Parameters)
        self.edt_console.setEnabled(False)
        self.edt_console.setTabStopWidth(80)
        self.edt_console.setObjectName("edt_console")
        self.verticalLayout.addWidget(self.edt_console)
        self.tabWidget_General.addTab(self.tab_Parameters, "")
        self.tab_Config = QtWidgets.QWidget()
        self.tab_Config.setObjectName("tab_Config")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_Config)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_AppLogLevels = QtWidgets.QLabel(self.tab_Config)
        self.label_AppLogLevels.setObjectName("label_AppLogLevels")
        self.verticalLayout_2.addWidget(self.label_AppLogLevels)
        self.listWidget_LogLevels = QtWidgets.QListWidget(self.tab_Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_LogLevels.sizePolicy().hasHeightForWidth())
        self.listWidget_LogLevels.setSizePolicy(sizePolicy)
        self.listWidget_LogLevels.setMinimumSize(QtCore.QSize(0, 80))
        self.listWidget_LogLevels.setMaximumSize(QtCore.QSize(16777215, 80))
        self.listWidget_LogLevels.setLineWidth(1)
        self.listWidget_LogLevels.setProperty("showDropIndicator", False)
        self.listWidget_LogLevels.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidget_LogLevels.setAlternatingRowColors(False)
        self.listWidget_LogLevels.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_LogLevels.setProperty("isWrapping", True)
        self.listWidget_LogLevels.setResizeMode(QtWidgets.QListView.Fixed)
        self.listWidget_LogLevels.setLayoutMode(QtWidgets.QListView.Batched)
        self.listWidget_LogLevels.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget_LogLevels.setModelColumn(0)
        self.listWidget_LogLevels.setSelectionRectVisible(True)
        self.listWidget_LogLevels.setObjectName("listWidget_LogLevels")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget_LogLevels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget_LogLevels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget_LogLevels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Checked)
        self.listWidget_LogLevels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget_LogLevels.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget_LogLevels.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget_LogLevels)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_Exclusions = QtWidgets.QLabel(self.tab_Config)
        self.label_Exclusions.setObjectName("label_Exclusions")
        self.verticalLayout_4.addWidget(self.label_Exclusions)
        self.edt_Exclusions = QtWidgets.QPlainTextEdit(self.tab_Config)
        self.edt_Exclusions.setObjectName("edt_Exclusions")
        self.verticalLayout_4.addWidget(self.edt_Exclusions)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_Categories = QtWidgets.QLabel(self.tab_Config)
        self.label_Categories.setObjectName("label_Categories")
        self.verticalLayout_3.addWidget(self.label_Categories)
        self.edt_Categories = QtWidgets.QPlainTextEdit(self.tab_Config)
        self.edt_Categories.setObjectName("edt_Categories")
        self.verticalLayout_3.addWidget(self.edt_Categories)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.tabWidget_General.addTab(self.tab_Config, "")
        self.verticalLayout_5.addWidget(self.tabWidget_General)
        self.horizontalLayout_statusbar = QtWidgets.QHBoxLayout()
        self.horizontalLayout_statusbar.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_statusbar.setSpacing(0)
        self.horizontalLayout_statusbar.setObjectName("horizontalLayout_statusbar")
        self.frame_files = QtWidgets.QFrame(self.centralWidget)
        self.frame_files.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_files.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_files.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_files.setObjectName("frame_files")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_files)
        self.horizontalLayout_6.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_10 = QtWidgets.QLabel(self.frame_files)
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.lbl_processed_files = QtWidgets.QLabel(self.frame_files)
        self.lbl_processed_files.setObjectName("lbl_processed_files")
        self.horizontalLayout_6.addWidget(self.lbl_processed_files)
        self.label_12 = QtWidgets.QLabel(self.frame_files)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.lbl_total_files = QtWidgets.QLabel(self.frame_files)
        self.lbl_total_files.setObjectName("lbl_total_files")
        self.horizontalLayout_6.addWidget(self.lbl_total_files)
        self.horizontalLayout_statusbar.addWidget(self.frame_files)
        self.frame_lines = QtWidgets.QFrame(self.centralWidget)
        self.frame_lines.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_lines.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lines.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lines.setObjectName("frame_lines")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_lines)
        self.horizontalLayout_7.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_lines)
        self.label_11.setScaledContents(False)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.lbl_processed_lines = QtWidgets.QLabel(self.frame_lines)
        self.lbl_processed_lines.setObjectName("lbl_processed_lines")
        self.horizontalLayout_7.addWidget(self.lbl_processed_lines)
        self.label_9 = QtWidgets.QLabel(self.frame_lines)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.lbl_total_lines = QtWidgets.QLabel(self.frame_lines)
        self.lbl_total_lines.setObjectName("lbl_total_lines")
        self.horizontalLayout_7.addWidget(self.lbl_total_lines)
        self.horizontalLayout_statusbar.addWidget(self.frame_lines)
        self.frame_log_entries = QtWidgets.QFrame(self.centralWidget)
        self.frame_log_entries.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_log_entries.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_log_entries.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_log_entries.setObjectName("frame_log_entries")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_log_entries)
        self.horizontalLayout_5.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_log_entries_count = QtWidgets.QLabel(self.frame_log_entries)
        self.lbl_log_entries_count.setObjectName("lbl_log_entries_count")
        self.horizontalLayout_5.addWidget(self.lbl_log_entries_count)
        self.label_15 = QtWidgets.QLabel(self.frame_log_entries)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_5.addWidget(self.label_15)
        self.horizontalLayout_statusbar.addWidget(self.frame_log_entries)
        self.frame_elapsed_time = QtWidgets.QFrame(self.centralWidget)
        self.frame_elapsed_time.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_elapsed_time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_elapsed_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_elapsed_time.setObjectName("frame_elapsed_time")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_elapsed_time)
        self.horizontalLayout_8.setContentsMargins(6, 0, 6, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.frame_elapsed_time)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.lbl_elapsed_time = QtWidgets.QLabel(self.frame_elapsed_time)
        self.lbl_elapsed_time.setObjectName("lbl_elapsed_time")
        self.horizontalLayout_8.addWidget(self.lbl_elapsed_time)
        self.horizontalLayout_statusbar.addWidget(self.frame_elapsed_time)
        self.frame_progress_bar = QtWidgets.QFrame(self.centralWidget)
        self.frame_progress_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_progress_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_progress_bar.setObjectName("frame_progress_bar")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_progress_bar)
        self.horizontalLayout_9.setContentsMargins(2, 0, 2, 0)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.progressBar = QtWidgets.QProgressBar(self.frame_progress_bar)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_9.addWidget(self.progressBar)
        self.horizontalLayout_statusbar.addWidget(self.frame_progress_bar)
        self.verticalLayout_5.addLayout(self.horizontalLayout_statusbar)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1256, 22))
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuRun = QtWidgets.QMenu(self.menuBar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setIconSize(QtCore.QSize(32, 32))
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/shutdown_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon1)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSave_config_to_file = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Arrow-down-icon_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_config_to_file.setIcon(icon2)
        self.actionSave_config_to_file.setObjectName("actionSave_config_to_file")
        self.actionLoad_config_from_file = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Arrow-up-icon_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad_config_from_file.setIcon(icon3)
        self.actionLoad_config_from_file.setObjectName("actionLoad_config_from_file")
        self.actionParse = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Categories-preferences-system-icon_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionParse.setIcon(icon4)
        self.actionParse.setIconVisibleInMenu(True)
        self.actionParse.setPriority(QtWidgets.QAction.NormalPriority)
        self.actionParse.setObjectName("actionParse")
        self.actionClean_logs = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/bin-red-full-icon_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClean_logs.setIcon(icon5)
        self.actionClean_logs.setObjectName("actionClean_logs")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionSelect_Folder = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/folder_search_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSelect_Folder.setIcon(icon6)
        self.actionSelect_Folder.setObjectName("actionSelect_Folder")
        self.actionRecursive = QtWidgets.QAction(MainWindow)
        self.actionRecursive.setCheckable(True)
        self.actionRecursive.setObjectName("actionRecursive")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/stop_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon7)
        self.actionStop.setObjectName("actionStop")
        self.menuFile.addAction(self.actionQuit)
        self.menuOptions.addAction(self.actionSave_config_to_file)
        self.menuOptions.addAction(self.actionLoad_config_from_file)
        self.menuRun.addAction(self.actionParse)
        self.menuRun.addAction(self.actionClean_logs)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionSelect_Folder)
        self.menuRun.addAction(self.actionRecursive)
        self.menuRun.addSeparator()
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.mainToolBar.addAction(self.actionQuit)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionSelect_Folder)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionParse)
        self.mainToolBar.addAction(self.actionStop)
        self.mainToolBar.addAction(self.actionClean_logs)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionSave_config_to_file)
        self.mainToolBar.addAction(self.actionLoad_config_from_file)

        self.retranslateUi(MainWindow)
        self.tabWidget_General.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget_General, self.edt_Path)
        MainWindow.setTabOrder(self.edt_Path, self.btn_SelectDir)
        MainWindow.setTabOrder(self.btn_SelectDir, self.date_To)
        MainWindow.setTabOrder(self.date_To, self.spin_perfTrigger)
        MainWindow.setTabOrder(self.spin_perfTrigger, self.spin_contextLOL)
        MainWindow.setTabOrder(self.spin_contextLOL, self.edt_output)
        MainWindow.setTabOrder(self.edt_output, self.chk_AutoOpen)
        MainWindow.setTabOrder(self.chk_AutoOpen, self.edt_console)
        MainWindow.setTabOrder(self.edt_console, self.edt_Exclusions)
        MainWindow.setTabOrder(self.edt_Exclusions, self.edt_Categories)
        MainWindow.setTabOrder(self.edt_Categories, self.listWidget_LogLevels)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Log Parser V5"))
        self.label.setText(_translate("MainWindow", "Path:   "))
        self.btn_SelectDir.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", " From:"))
        self.date_From.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_3.setText(_translate("MainWindow", " To:"))
        self.date_To.setDisplayFormat(_translate("MainWindow", "yyyy/MM/dd"))
        self.label_6.setText(_translate("MainWindow", "Performance Trigger:"))
        self.label_7.setText(_translate("MainWindow", "sec "))
        self.label_4.setText(_translate("MainWindow", "Context:"))
        self.label_5.setText(_translate("MainWindow", "previous lines"))
        self.chk_splitFilePath.setText(_translate("MainWindow", "Split File Path"))
        self.label_8.setText(_translate("MainWindow", "Output: "))
        self.chk_AutoOpen.setText(_translate("MainWindow", "Open resulting excel file"))
        self.tabWidget_General.setTabText(self.tabWidget_General.indexOf(self.tab_Parameters), _translate("MainWindow", "Parsing"))
        self.label_AppLogLevels.setText(_translate("MainWindow", "Log Levels:"))
        self.listWidget_LogLevels.setSortingEnabled(False)
        __sortingEnabled = self.listWidget_LogLevels.isSortingEnabled()
        self.listWidget_LogLevels.setSortingEnabled(False)
        item = self.listWidget_LogLevels.item(0)
        item.setText(_translate("MainWindow", "LOG"))
        item = self.listWidget_LogLevels.item(1)
        item.setText(_translate("MainWindow", "FATAL"))
        item = self.listWidget_LogLevels.item(2)
        item.setText(_translate("MainWindow", "EXCEPTION_TRACK"))
        item = self.listWidget_LogLevels.item(3)
        item.setText(_translate("MainWindow", "LEAK"))
        item = self.listWidget_LogLevels.item(4)
        item.setText(_translate("MainWindow", "WARNING"))
        item = self.listWidget_LogLevels.item(5)
        item.setText(_translate("MainWindow", "STATISTICS"))
        self.listWidget_LogLevels.setSortingEnabled(__sortingEnabled)
        self.label_Exclusions.setText(_translate("MainWindow", "Exclusions:"))
        self.label_Categories.setText(_translate("MainWindow", "Categories:"))
        self.tabWidget_General.setTabText(self.tabWidget_General.indexOf(self.tab_Config), _translate("MainWindow", "Configuration"))
        self.label_10.setText(_translate("MainWindow", "Files processed: "))
        self.lbl_processed_files.setText(_translate("MainWindow", "."))
        self.label_12.setText(_translate("MainWindow", "/"))
        self.lbl_total_files.setText(_translate("MainWindow", "."))
        self.label_11.setText(_translate("MainWindow", "Lines processed: "))
        self.lbl_processed_lines.setText(_translate("MainWindow", "."))
        self.label_9.setText(_translate("MainWindow", "/"))
        self.lbl_total_lines.setText(_translate("MainWindow", "."))
        self.lbl_log_entries_count.setText(_translate("MainWindow", "."))
        self.label_15.setText(_translate("MainWindow", " log entries to analyze"))
        self.label_13.setText(_translate("MainWindow", "Elapsed Time: "))
        self.lbl_elapsed_time.setText(_translate("MainWindow", "."))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Alt+Q"))
        self.actionSave_config_to_file.setText(_translate("MainWindow", "Save options to file..."))
        self.actionLoad_config_from_file.setText(_translate("MainWindow", "Load options from file..."))
        self.actionParse.setText(_translate("MainWindow", "Parse"))
        self.actionParse.setIconText(_translate("MainWindow", "Parse"))
        self.actionParse.setShortcut(_translate("MainWindow", "Alt+R"))
        self.actionClean_logs.setText(_translate("MainWindow", "Clean logs"))
        self.actionClean_logs.setToolTip(_translate("MainWindow", "Clean log files"))
        self.action_2.setText(_translate("MainWindow", "-"))
        self.actionSelect_Folder.setText(_translate("MainWindow", "Select Folder..."))
        self.actionRecursive.setText(_translate("MainWindow", "Recursive"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setToolTip(_translate("MainWindow", "Stop log file parsing"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

